### Today Topics
- Introduction to Data Science
- Data Science means study of data which involves 3 stages.
    - Analysis,manipulation and cleaning
    - Analysis means analyzing the data
    - Manipulation involves modification of data
    - Cleaning means removing unnecessary data items
    - What is this study ?
        - The analysis of data
            - 1 Student details: personal information
                - Name,Roll_num,dept,year,college:academic details
                - Name,Mobile,photo,Contact address
            - College Data
                - Director,Principal,Vice Principal,HOD,Staff,Students,Workers etc..
                    - students:1000:5 branches: 4 years
                    - Principla:Name,Identity/Degrees/working experience,subject
                    - huge amount of data exist.
    - What is a data ?
        - related information used for perticular purpose and belongs to some category
            - College data
        - What is information ?
            -  The thing/matter whatever is in a perticular place/local machine
  - int,floats,str,files of different types
  
- **Numpy** module
- Is one of the most important data science modules
    - Numpy module numeric python or numerical python which is used to work with n dimensional arrays and also supports scientific computation .
    - array type of data
    - module,packages,libraries
    
- Installation of Numpy
    - 1) numpy module is to installed in our local machine
         - pip install numpy (IDLE)
    - 2) Need to import the features of perticular module in our workspace
        - import numpy 
        - import numpy as np (np is the var that represents entire numpy module)

In [12]:
import numpy

In [13]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

#### Arrays()
- numpy.array() 
- array is nothing but matrix

In [15]:
# creating arrays using string
s=numpy.array("Hi I am Ruthu from APSSDC")
s

array('Hi I am Ruthu from APSSDC', dtype='<U25')

In [17]:
# creating arrays using string
s2=numpy.array("Hi I am Ruthu from APSSDC".split()) 
print(s2) # row matrix

['Hi' 'I' 'am' 'Ruthu' 'from' 'APSSDC']


In [21]:
li=[3,4,5,6] # list 
print(numpy.array(li)) # array

[3 4 5 6]


In [22]:
# creating arrays using tuple
t=numpy.array(("ruthu",123,90.45,'hi')) # homogenous data structure
t

array(['ruthu', '123', '90.45', 'hi'], dtype='<U5')

In [25]:
# how to create column matrix
col=numpy.array([[10],[34],[56]])
print(col) # column matrix

[[10]
 [34]
 [56]]


In [31]:
# how to create column matrix
col2=numpy.array([(4),(5),(6),(9)])
print(col2) # row matrix

[4 5 6 9]


In [33]:
# creating 2D arrays
# 2 dimensional arrays:row and column
ar=numpy.array([[2,3,8],[9,8,5]]) # 2x3
print(ar)

[[2 3 8]
 [9 8 5]]


### create arrays using range() in python
- range(upper)
- range(lw,up)
- range(lw,up,step_count)

In [35]:
r=numpy.array(range(10))
print(r)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
r2=numpy.array(range(10,50))
r2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [37]:
r3=numpy.array(range(10,40,3))
r3

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [38]:
numpy.__version__ #version of numpy

'1.16.5'

In [39]:
r3.dtype # datatypes present in var

dtype('int32')

In [40]:
r3.shape # (row,col)

(10,)

In [42]:
r2.size # no.of items present in var

40

In [43]:
r2.itemsize # size of each item in var

4

In [44]:
r2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### arange()
- we can create the arrays with the help of arange() sub module in numpy module
- similar to range() in python

In [47]:
ar=numpy.arange(30)
print(ar)
print(numpy.arange(40,int(input("upper bound:"))))
print(numpy.arange(50,100,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
upper bound:90
[40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87
 88 89]
[50 53 56 59 62 65 68 71 74 77 80 83 86 89 92 95 98]


#### linspace()
- create the arrays using linspace
- contains 2 arguments but both limits are inclusive

In [48]:
ln=numpy.linspace(2,3) # 2 and 3
ln

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [50]:
ln2=numpy.linspace(2,6,4) # 4 many partitions in range of 2 and 3
ln2

array([2.        , 3.33333333, 4.66666667, 6.        ])

In [51]:
2,3,4,5,6 # 5 values to be 4 partitions


(2, 3, 4, 5, 6)

In [52]:
5/4

1.25

#### random()
- we can create random matrix also
- numpy.random()
    - random.randint()
        - can be arranged 3 types
    - random.random()
    - random.rand()
    - random.randn()

In [53]:
import numpy as np

In [72]:
rn=np.random.randint(780) # 10 
rn

161

In [75]:
rn2=np.random.randint(10,50)
rn2

11

In [82]:
rn3=np.random.randint(20,100,12) # will generate 7 random values within this range
rn3

array([48, 58, 21, 60, 52, 95, 58, 28, 45, 25, 29, 42])

In [92]:
rn4=np.random.random(17) # it will generate 17 many values in range of 0 and 1
rn4

array([0.21541139, 0.39032638, 0.94156151, 0.26406802, 0.68750483,
       0.94818656, 0.50089373, 0.0313865 , 0.51305666, 0.71867418,
       0.27746808, 0.55818844, 0.49517775, 0.64743565, 0.06134606,
       0.55107028, 0.99168065])

In [101]:
rn5=np.random.rand(1) # it will give random value in b/w 0 and 1
rn5

array([0.60548863])

In [103]:
rn6=np.random.randn(1) # -1 to +1
rn6

array([-0.81966695])

### reshape()
- we can reshape existed matrix
- numpy.reshape(row,col)

In [111]:
ar=np.arange(10,30) # 20 values
print(ar)
print(ar.reshape(4,5)) #20:(1,20),(2,10),(4,5),(5,4),(10,2),(20,1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [113]:
r=np.random.randint(50,100,20)
r.reshape(4,5) # both row and col mentioned here

array([[91, 94, 83, 66, 72],
       [69, 97, 68, 85, 50],
       [63, 81, 93, 82, 77],
       [67, 82, 75, 96, 85]])

In [114]:
# 20 
r.reshape(5,-1) # -ve value indicated the unknown value

array([[91, 94, 83, 66],
       [72, 69, 97, 68],
       [85, 50, 63, 81],
       [93, 82, 77, 67],
       [82, 75, 96, 85]])

In [116]:
print(r.reshape(10,-5))

[[91 94]
 [83 66]
 [72 69]
 [97 68]
 [85 50]
 [63 81]
 [93 82]
 [77 67]
 [82 75]
 [96 85]]


In [117]:
print(r.reshape(-2,10)) # 10 columns in each row

[[91 94 83 66 72 69 97 68 85 50]
 [63 81 93 82 77 67 82 75 96 85]]


In [121]:
o=np.ones(4) # array is filled with only 1
o

array([1., 1., 1., 1.])

In [124]:
one=np.ones((4,5)) # 4x5
one # ones matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [125]:
z=np.zeros(7)
z

array([0., 0., 0., 0., 0., 0., 0.])

In [126]:
zero=np.zeros((3,2))
zero # zeros matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [127]:
 # identity matrix
eye=np.eye(3) # 3x3 matrix
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [128]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [134]:
print(np.diag([3,4,10])) # creating the diagonal matrix

[[ 3  0  0]
 [ 0  4  0]
 [ 0  0 10]]


In [135]:
print(np.diag(['hi','hello','hey']))

[['hi' '' '']
 ['' 'hello' '']
 ['' '' 'hey']]


In [137]:
ran=r.reshape(4,5)
ran

array([[91, 94, 83, 66, 72],
       [69, 97, 68, 85, 50],
       [63, 81, 93, 82, 77],
       [67, 82, 75, 96, 85]])

In [138]:
print(np.diag(ran)) # diagonal elements of ran
# 00 11 22 33 44

[91 97 93 96]


### Accessing the array 
- by using slicing
- retrieving subpart in entire iterable using index
- 2 types:+ve and -ve
    - 0 to len(iterable)-1
    - -1 to -infinite

In [139]:
ran

array([[91, 94, 83, 66, 72],
       [69, 97, 68, 85, 50],
       [63, 81, 93, 82, 77],
       [67, 82, 75, 96, 85]])

In [140]:
ran[0] # 1st row

array([91, 94, 83, 66, 72])

In [141]:
ran[1]

array([69, 97, 68, 85, 50])

In [142]:
ran[-1] # last row

array([67, 82, 75, 96, 85])

In [143]:
ran[:]

array([[91, 94, 83, 66, 72],
       [69, 97, 68, 85, 50],
       [63, 81, 93, 82, 77],
       [67, 82, 75, 96, 85]])

In [144]:
ran[::]

array([[91, 94, 83, 66, 72],
       [69, 97, 68, 85, 50],
       [63, 81, 93, 82, 77],
       [67, 82, 75, 96, 85]])

In [145]:
ran[::-1]

array([[67, 82, 75, 96, 85],
       [63, 81, 93, 82, 77],
       [69, 97, 68, 85, 50],
       [91, 94, 83, 66, 72]])

In [146]:
# 2d indexing
ran[1][2] # accesing 3rd column value in 2nd row

68

In [148]:
ran[:,1:4] # the middle 3 column values in all rows

array([[94, 83, 66],
       [97, 68, 85],
       [81, 93, 82],
       [82, 75, 96]])

In [149]:
ran[1:4,2:4]

array([[68, 85],
       [93, 82],
       [75, 96]])

#### by using fancy indexing
- condition based indexing

In [151]:
ran>60 # 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [152]:
ran[ran>60] # fancy indexing

array([91, 94, 83, 66, 72, 69, 97, 68, 85, 63, 81, 93, 82, 77, 67, 82, 75,
       96, 85])

### Scientific Computation
- arithmetic operations 

In [153]:
ran

array([[91, 94, 83, 66, 72],
       [69, 97, 68, 85, 50],
       [63, 81, 93, 82, 77],
       [67, 82, 75, 96, 85]])

In [159]:
ar=np.arange(10,30).reshape(4,5)

In [160]:
print(ar)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [162]:
print(ran+ar)
print(ran-ar)
print(ran*ar)
print(ran/ar)

[[101 105  95  79  86]
 [ 84 113  85 103  69]
 [ 83 102 115 105 101]
 [ 92 108 102 124 114]]
[[81 83 71 53 58]
 [54 81 51 67 31]
 [43 60 71 59 53]
 [42 56 48 68 56]]
[[ 910 1034  996  858 1008]
 [1035 1552 1156 1530  950]
 [1260 1701 2046 1886 1848]
 [1675 2132 2025 2688 2465]]
[[9.1        8.54545455 6.91666667 5.07692308 5.14285714]
 [4.6        6.0625     4.         4.72222222 2.63157895]
 [3.15       3.85714286 4.22727273 3.56521739 3.20833333]
 [2.68       3.15384615 2.77777778 3.42857143 2.93103448]]


In [164]:
print(ran.min())

50


In [179]:
ran.mean() # sum of values/no.of values

78.8

In [165]:
ran.max() # maximum value

97

#### broadcasting in numpy
- appling scalar value on entire varable

In [178]:
ran.sum() # summation of values

1576

In [168]:
print(ar+10) # 10 is adding to every element in the array

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [169]:
print(ran+19)

[[110 113 102  85  91]
 [ 88 116  87 104  69]
 [ 82 100 112 101  96]
 [ 86 101  94 115 104]]


### Logarithms and Exponentials

In [171]:
np.log(10)

2.302585092994046

In [172]:
np.log(1)

0.0

In [173]:
np.log(0) # base is 10

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [174]:
np.log2(2)

1.0

In [175]:
np.exp(2)

7.38905609893065

In [176]:
np.exp(np.log(1)) # finding the exponential value of log 1

1.0

In [177]:
np.log(np.exp(2)) # finding the logarithemic value of exponential value

2.0